name:  project
description: 
version: 1.0
license: Proprietary
author: Ryan J. Cooke
services:
  generateProjectCreate:
    authenticator: ExpressAuthentication
  generateProjectDelete:
    authenticator: ExpressAuthentication
  generateProjectUpdate:
    authenticator: ExpressAuthentication