name:  Service
description: 
version: 1.0
license: Proprietary
author: Ryan J. Cooke
services:
  createServiceConfigurableType:
    authenticator: ExpressAuthentication
  deleteServiceConfigurableType:
    authenticator: ExpressAuthentication
  readAllServiceConfigurableTypes:
    authenticator: ExpressAuthentication
  readServiceConfigurableType:
    authenticator: ExpressAuthentication
  updateServiceConfigurableType:
    authenticator: ExpressAuthentication