name:  Generate Connections Service
description: 
version: 1.0
license: Proprietary
author: Ryan J. Cooke
services:
  generateConnectionAll:
    authenticator: ExpressAuthentication
  generateConnectionDelete:
    authenticator: ExpressAuthentication
  generateConnectionCreateUpdate:
    authenticator: ExpressAuthentication