name:  Service
description: 
version: 1.0
license: Proprietary
author: Ryan J. Cooke
services:
  allTeams:
    authenticator: ExpressAuthentication
  createTeam:
    authenticator: ExpressAuthentication
  deleteTeam:
    authenticator: ExpressAuthentication