name:  Service
description: 
version: 1.0
license: Proprietary
author: Ryan J. Cooke
services:
  generateDatasourceAll:
    authenticator: ExpressAuthentication
  generateDatasourceDelete:
    authenticator: ExpressAuthentication
  generateDatasourceRefresh:
    authenticator: ExpressAuthentication
  generateDatasourceCreateUpdate:
    authenticator: ExpressAuthentication