name:  Service
description: 
version: 1.0
license: Proprietary
author: Ryan J. Cooke
services:
  createValueStore:
    authenticator: ExpressAuthentication
  deleteValueStore:
    authenticator: ExpressAuthentication
  readValueStore:
    authenticator: ExpressAuthentication
  updateValueStore:
    authenticator: ExpressAuthentication