name:  Service
description: 
version: 1.0
license: Proprietary
author: Ryan J. Cooke
services:
  createUpdateStoreServ:
    authenticator: ExpressAuthentication
  deleteStoreServ:
    authenticator: ExpressAuthentication