name:  Service
description: 
version: 1.0
license: Proprietary
author: Ryan J. Cooke
services:
  createBlActionResponseType:
    authenticator: ExpressAuthentication
  deleteBlActionResponseType:
    authenticator: ExpressAuthentication
  readAllBlActionResponseTypes:
    authenticator: ExpressAuthentication
  readBlActionResponseType:
    authenticator: ExpressAuthentication
  updateBlActionResponseType:
    authenticator: ExpressAuthentication