name: General Rest Endpoints (Default for all MISC)
description: This is a general service in which we use for all misc endpoints that we need and manually manage
version: 1.0
license: Not MIT
author: Ryan J. Cooke
services:
  allNotifications:
    authenticator: ExpressAuthentication