// I'd
// I should
// I might
// I could
// I may
// I shall
// I can
// I will possibly
// I could potentially
// I might conceivably
// I may very well
// I should perhaps
// I will likely
// I would potentially
// I could conceivably
// I might potentially
// I may potentially
// I shall potentially
// I will conceivably
// I would likely
// I could likely
// I might likely
// I may likely
// I shall likely
// I will perhaps
// I would perhaps
// I could perhaps
// I might perhaps
// I may perhaps
// I shall perhaps

const waysToSayYouWould = [
    `you'd`,
    'you would',
    `you'll`,
    'you will',
    'you will probably ',
    'you will likely ',
    'you will most likely ',
    'you will certainly ',
    'you will definitely ',
    'you will undoubtedly ',
    'you will assuredly ',
    'you will positively ',
    'you will absolutely ',
    'you will surely ',
    'you will undoubtedly ',
    'you will doubtless ',
    'you will for sure ',
    'you will for certain ',
    'you will for a fact ',
    'you will for certain ',
    'you will beyond doubt ',
    'you will beyond any doubt '
];


export default [
    {
        term: ' ',
        matches: [
            '  ',
            '   ',
            '    ',
            '     ',
            '      ',
            '       ',
        ]
    },
    {
        term: 'I would ',
        matches: [
            'i should ',
            'i might ',
            'i could ',
            'i may ',
            'i shall ',
            'i can ',
            'i will possibly ',
            'i could potentially ',
            'i might conceivably ',
            'i may very well ',
            'i should perhaps ',
            'i will likely ',
            'i would potentially ',
            'i could conceivably ',
            'i might potentially ',
            'i may potentially ',
            'i shall potentially ',
            'i will conceivably ',
            'i would likely ',
            'i could likely ',
            'i might likely ',
            'i may likely ',
            'i shall likely ',
            'i will perhaps ',
            'i would perhaps ',
            'i could perhaps ',
            'i might perhaps ',
            'i may perhaps ',
            'i shall perhaps ',
            `i'd `,
            'id ',
        ]
    },
    {
        term: 'I will ',
        matches: [
            'i shall ',
            `i'm going to `,
            'i am going to ',
            `i'm gonna `,
            'i am gonna ',
            'i intend to ',
            'i plan to ',
            'i aim to ',
            `i'm about to `,
            'i am about to ',
            `i'll be `,
            'i shall be ',
            'i will probably ',
            'i will likely ',
            'i will most likely ',
            'i will certainly ',
            'i will definitely ',
            'i will undoubtedly ',
            'i will assuredly ',
            'i will positively ',
            'i will absolutely ',
            'i will surely ',
            'i will undoubtedly ',
            'i will doubtless ',
            'i will for sure ',
            'i will for certain ',
            'i will for a fact ',
            'i will for certain ',
            'i will beyond doubt ',
            'i will beyond any doubt ',
            `i'll `,
        ]
    },
    {
        term: 'you would ',
        matches: [
            'you will probably ',
            'you will likely ',
            'you will most likely ',
            'you will certainly ',
            'you will definitely ',
            'you will undoubtedly ',
            'you will assuredly ',
            'you will positively ',
            'you will absolutely ',
            'you will surely ',
            'you will undoubtedly ',
            'you will doubtless ',
            'you will for sure ',
            'you will for certain ',
            'you will for a fact ',
            'you will for certain ',
            'you will beyond doubt ',
            'you will beyond any doubt ',
            'you would ',
            'you will ',
            `you'd`,
            `you'll`,
        ]
    },
    {
        term: 'he would ',
        matches: [
            'he will probably ',
            'he will likely ',
            'he will most likely ',
            'he will certainly ',
            'he will definitely ',
            'he will undoubtedly ',
            'he will assuredly ',
            'he will positively ',
            'he will absolutely ',
            'he will surely ',
            'he will undoubtedly ',
            'he will doubtless ',
            'he will for sure ',
            'he will for certain ',
            'he will for a fact ',
            'he will for certain ',
            'he will beyond doubt ',
            'he will beyond any doubt ',
            `he'd `,
            'he would ',
            `he'll `,
            'he will ',
        ]
    },
    {
        term: 'she would ',
        matches: [
            'she will probably ',
            'she will likely ',
            'she will most likely ',
            'she will certainly ',
            'she will definitely ',
            'she will undoubtedly ',
            'she will assuredly ',
            'she will positively ',
            'she will absolutely ',
            'she will surely ',
            'she will undoubtedly ',
            'she will doubtless ',
            'she will for sure ',
            'she will for certain ',
            'she will for a fact ',
            'she will for certain ',
            'she will beyond doubt ',
            'she will beyond any doubt ',
            `she'd `,
            'she would ',
            `she'll `,
            'she will ',
        ]
    },
    {
        term: 'it would',
        matches: [
            'it will probably ',
            'it will likely ',
            'it will most likely ',
            'it will certainly ',
            'it will definitely ',
            'it will undoubtedly ',
            'it will assuredly ',
            'it will positively ',
            'it will absolutely ',
            'it will surely ',
            'it will undoubtedly ',
            'it will doubtless ',
            'it will for sure ',
            'it will for certain ',
            'it will for a fact ',
            'it will for certain ',
            'it will beyond doubt ',
            'it will beyond any doubt ',
            `it'd `,
            'it would ',
            `it'll `,
            'it will ',
        ]
    },
    {
        term: 'we would ',
        matches: [
            'we will probably ',
            'we will likely ',
            'we will most likely ',
            'we will certainly ',
            'we will definitely ',
            'we will undoubtedly ',
            'we will assuredly ',
            'we will positively ',
            'we will absolutely ',
            'we will surely ',
            'we will undoubtedly ',
            'we will doubtless ',
            'we will for sure ',
            'we will for certain ',
            'we will for a fact ',
            'we will for certain ',
            'we will beyond doubt ',
            'we will beyond any doubt ',
            `we'd `,
            'we would ',
            `we'll `,
            'we will ',
        ]
    },
    {
        term: 'they would ',
        matches: [
            'they will probably ',
            'they will likely ',
            'they will most likely ',
            'they will certainly ',
            'they will definitely ',
            'they will undoubtedly ',
            'they will assuredly ',
            'they will positively ',
            'they will absolutely ',
            'they will surely ',
            'they will undoubtedly ',
            'they will doubtless ',
            'they will for sure ',
            'they will for certain ',
            'they will for a fact ',
            'they will for certain ',
            'they will beyond doubt ',
            'they will beyond any doubt ',
            `they'd `,
            'they would ',
            `they'll `,
            'they will ',
        ]
    },
    {
        term: 'you will ',
        matches: [
            'you will probably ',
            'you will likely ',
            'you will most likely ',
            'you will certainly ',
            'you will definitely ',
            'you will undoubtedly ',
            'you will assuredly ',
            'you will positively ',
            'you will absolutely ',
            'you will surely ',
            'you will undoubtedly ',
            'you will doubtless ',
            'you will for sure ',
            'you will for certain ',
            'you will for a fact ',
            'you will for certain ',
            'you will beyond doubt ',
            'you will beyond any doubt ',
            `you'll `,
            'you will ',
        ]
    },
    {
        term: 'he will ',
        matches: [
            'he will probably ',
            'he will most likely ',
            'he will certainly ',
            'he will definitely ',
            'he will undoubtedly ',
            'he will assuredly ',
            'he will positively ',
            'he will absolutely ',
            'he will surely ',
            'he will undoubtedly ',
            'he will doubtless ',
            'he will for sure ',
            'he will for certain ',
            'he will for a fact ',
            'he will for certain ',
            'he will beyond doubt ',
            'he will beyond any doubt ',
            'he will ',
            `he'll `,
        ]
    },
    {
        term: 'she will ',
        matches: [
            'she will probably ',
            'she will most likely ',
            'she will certainly ',
            'she will definitely ',
            'she will undoubtedly ',
            'she will assuredly ',
            'she will positively ',
            'she will absolutely ',
            'she will surely ',
            'she will undoubtedly ',
            'she will doubtless ',
            'she will for sure ',
            'she will for certain ',
            'she will for a fact ',
            'she will for certain ',
            'she will beyond doubt ',
            'she will beyond any doubt ',
            'she will ',
            `she'll `,
        ]
    },
    {
        term: 'it will ',
        matches: [
            'it will probably ',
            'it will most likely ',
            'it will certainly ',
            'it will definitely ',
            'it will undoubtedly ',
            'it will assuredly ',
            'it will positively ',
            'it will absolutely ',
            'it will surely ',
            'it will undoubtedly ',
            'it will doubtless ',
            'it will for sure ',
            'it will for certain ',
            'it will for a fact ',
            'it will for certain ',
            'it will beyond doubt ',
            'it will beyond any doubt ',
            'it will ',
            `it'll `,
        ]
    },
    {
        term: 'we will ',
        matches: [
            'we will probably ',
            'we will most likely ',
            'we will certainly ',
            'we will definitely ',
            'we will undoubtedly ',
            'we will assuredly ',
            'we will positively ',
            'we will absolutely ',
            'we will surely ',
            'we will undoubtedly ',
            'we will doubtless ',
            'we will for sure ',
            'we will for certain ',
            'we will for a fact ',
            'we will for certain ',
            'we will beyond doubt ',
            'we will beyond any doubt ',
            'we will ',
            `we'll `,
        ]
    },
    {
        term: 'they will ',
        matches: [
            'they will probably ',
            'they will most likely ',
            'they will certainly ',
            'they will definitely ',
            'they will undoubtedly ',
            'they will assuredly ',
            'they will positively ',
            'they will absolutely ',
            'they will surely ',
            'they will undoubtedly ',
            'they will doubtless ',
            'they will for sure ',
            'they will for certain ',
            'they will for a fact ',
            'they will for certain ',
            'they will beyond doubt ',
            'they will beyond any doubt ',
            'they will ',
            `they'll `,
        ]
    },
    {
        term: 'I want to ',
        matches: [
            `I'd like to `,
            'I would like to ',
            'I want to ',
            'I wish to ',
            'I desire to ',
            'I hope to ',
            'I fancy ',
            'I aspire to ',
            'I yearn to ',
            'I long to ',
            'I crave to ',
            'I hanker to ',
            'I covet to ',
            'I hunger to ',
            'I lust for ',
            'I thirst for ',
            'I ache for ',
            'I pine for ',
            'I yen for ',
            'I itch for ',
        ]
    },
    {
        term: '',
        matches: [
        ]
    },
    {
        term: '',
        matches: [
        ]
    },
    {
        term: '',
        matches: [
        ]
    },
]