name: Linter CRUD Service
description:
version: 1.0
license: Not MIT
author: Ryan J. Cooke
services:
  createConnection:
    authenticator: ExpressAuthentication
  deleteConnection:
    authenticator: ExpressAuthentication
  readAllConnections:
    authenticator: ExpressAuthentication
  readConnection:
    authenticator: ExpressAuthentication
  updateConnection:
    authenticator: ExpressAuthentication
  storeState2:
    authenticator: ExpressAuthentication