name:  Service
description: 
version: 1.0
license: Proprietary
author: Ryan J. Cooke
services:
  createAction:
    authenticator: ExpressAuthentication
  deleteAction:
    authenticator: ExpressAuthentication
  readAction:
    authenticator: ExpressAuthentication
  readActionAll:
    authenticator: ExpressAuthentication
  updateAction:
    authenticator: ExpressAuthentication