name: Linter CRUD Service
description:
version: 1.0
license: Not MIT
author: Ryan J. Cooke
services:
  createLinter:
    authenticator: ExpressAuthentication
  deleteLinter:
    authenticator: ExpressAuthentication
  readAllLinters:
    authenticator: ExpressAuthentication
  readLinter:
    authenticator: ExpressAuthentication
  updateLinter:
    authenticator: ExpressAuthentication