name:  Service
description: 
version: 1.0
license: Proprietary
author: Ryan J. Cooke
services:
  createNotification:
    authenticator: ExpressAuthentication
  deleteNotification:
    authenticator: ExpressAuthentication
  readNotificationAll:
    authenticator: ExpressAuthentication
  updateNotification:
    authenticator: ExpressAuthentication
  deleteAllNotifications:
    authenticator: ExpressAuthentication
  markAllAsRead:
    authenticator: ExpressAuthentication