name: ServiceConfig CRUD Service
description:
version: 1.0
license: Not MIT
author: Ryan J. Cooke
services:
  createServiceConfig:
    authenticator: ExpressAuthentication
  deleteServiceConfig:
    authenticator: ExpressAuthentication
  readAllServiceConfigs:
    authenticator: ExpressAuthentication
  readServiceConfig:
    authenticator: ExpressAuthentication
  updateServiceConfig:
    authenticator: ExpressAuthentication