name:  Service
description: 
version: 1.0
license: Proprietary
author: Ryan J. Cooke
services:
  generateMigrationCreate:
    authenticator: ExpressAuthentication
  generateMigrationSetup:
    authenticator: ExpressAuthentication
  generateMigrationUpdate:
    authenticator: ExpressAuthentication
  generateMigrationFiles:
    authenticator: ExpressAuthentication
  generateMigrationRun:
    authenticator: ExpressAuthentication