name:  Service
description: 
version: 1.0
license: Proprietary
author: Ryan J. Cooke
services:
  createServsGroup:
    authenticator: ExpressAuthentication
  deleteServsGroup:
    authenticator: ExpressAuthentication
  readServsGroupAll:
    authenticator: ExpressAuthentication
  updateServsGroup:
    authenticator: ExpressAuthentication
  publishServGroup:
    authenticator: ExpressAuthentication
  transformSgToStoreSg:
    authenticator: ExpressAuthentication